# Generated by Django 5.1 on 2024-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
                ('documento', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('assinatura', models.TextField()),
            ],
            options={
                'db_table': 'mercadolivre',
            },
        ),
        migrations.CreateModel(
            name='Shopee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
                ('documento', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('assinatura', models.TextField()),
            ],
            options={
                'db_table': 'shopee',
            },
        ),
    ]
