# Generated by Django 5.1 on 2024-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolivre',
            name='documento',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='shopee',
            name='documento',
            field=models.CharField(max_length=14),
        ),
    ]
