# Generated by Django 5.1 on 2024-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_mercadolivre_documento_alter_shopee_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolivre',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopee',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
