# Generated by Django 4.2 on 2024-10-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_alter_mercadolivre_data_alter_shopee_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadolivre',
            name='assinatura',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopee',
            name='assinatura',
            field=models.TextField(blank=True),
        ),
    ]
